server:
  port: 8080
spring:
  thymeleaf:
    prefix:
      classpath: /templates
  datasource:
    url: jdbc:mysql://localhost:3306/mini_blog?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456Aa
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapping/*.xml

swagger:
  enabled: true